### ISSUE TITLE
Race condition w.r.t. mongodb connector in loopback

### ISSUE THREAD

**Issue by mrquincle** [crownstone/crownstone-cloud#11]
It seems there is a race condition w.r.t. creating stones:

- https://github.com/crownstone/crownstone-cloud/blob/master/common/models/stone.js#L182

This is even though `validatesUniquenessOf` is called, which should work properly for the mongo connector. See [documentation](https://apidocs.strongloop.com/loopback-datasource-juggler/#validatable-validatesuniquenessof).

Should we and can we actually define `unique`ness on property level limited to a particular `[scope]` at:

- https://github.com/crownstone/crownstone-cloud/blob/master/common/models/stone.json

There seem to be a lot of issues with respect to this bug:

- https://github.com/strongloop/loopback/issues/1452
- https://github.com/strongloop/loopback-datasource-juggler/issues/892
- https://github.com/strongloop/loopback/issues/1637
- old: https://github.com/strongloop/loopback-datasource-juggler/issues/87

Sandbox at https://github.com/strongloop/loopback-sandbox/issues is with old loopback version.

If it is not solved within loopback, we will have to do it ourselves ([mongo docs](https://docs.mongodb.com/manual/tutorial/perform-two-phase-commits/)).

**Comment by AlexDM0** [comment]
Has been fixed and pushed to develop and release. The scope is different from the uniqueness option if we define it in the json. Currently we check after saving if the entry is unique, if not, make it so. It's kind of dirty but for now it works.
