### ISSUE TITLE
Add retry options

### ISSUE THREAD

**Issue by mrquincle** [crownstone/crownstone-cloud#4]
Currently, when the database server fails the mongodb loopback connector does not default to any retries.

Add parameters to https://github.com/crownstone/crownstone-cloud/blob/master/server/datasources.production.js explicitly, such as:

	"autoReconnect": true,
	"reconnectTries": 60,
	"reconnectInterval": 100

I don't know the exact fields by the way. At http://mongodb.github.io/node-mongodb-native/2.0/tutorials/connection_failures/ I see `autoReconnect`. The other ones might not exist or have different names.

Other source: http://mongodb.github.io/node-mongodb-native/core/tutorials/connecting/

I'm also not certain if these configuration values are picked up and passed properly. At https://github.com/strongloop/loopback-connector-mongodb/issues/333 they suggest that that is the case.

**Comment by AlexDM0** [comment]
I've added it to our pivotal tracker
