### ISSUE TITLE
No mongodb error on GET profilePic

### ISSUE THREAD

**Issue by mrquincle** [crownstone/crownstone-cloud#9]
This should be gracefully handled:

- Caller should not call end point to retrieve picture, but first check if `profilePicId` is actually non-empty.
- If resource does not exist, handle this in loopback, don't retrieve it from mongo with "File not found error" messages screwing up the logs.

**Comment by AlexDM0** [comment]
it *is* handled properly. What you see in the logs is due to the logging flag of the error handler. We will have to check if we need this flag.
